package myProj;

//import java.awt.event.ItemEvent;
import java.text.DecimalFormat;

/**
 *
 * @author Michael Thammavong
 */
public class LunchMenu extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form LunchMenu
     */
    public LunchMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
  private void initComponents()
  {

    btnGpMain = new javax.swing.ButtonGroup();
    jpMainCourse = new javax.swing.JPanel();
    rbHamburger = new javax.swing.JRadioButton();
    rbPizza = new javax.swing.JRadioButton();
    rbSalad = new javax.swing.JRadioButton();
    layerPane1 = new javax.swing.JLayeredPane();
    jpAddons = new javax.swing.JPanel();
    chkLettuce = new javax.swing.JCheckBox();
    chkMayonnaise = new javax.swing.JCheckBox();
    chkMustard = new javax.swing.JCheckBox();
    jpAddons2 = new javax.swing.JPanel();
    chkPepperoni = new javax.swing.JCheckBox();
    chkSausage = new javax.swing.JCheckBox();
    chkMushrooms = new javax.swing.JCheckBox();
    jpAddons3 = new javax.swing.JPanel();
    chkCroutons = new javax.swing.JCheckBox();
    chkBacon = new javax.swing.JCheckBox();
    chkBread = new javax.swing.JCheckBox();
    jpSubTotal = new javax.swing.JPanel();
    lblSubTotal = new javax.swing.JLabel();
    txtSubTotal = new javax.swing.JTextField();
    lblTax = new javax.swing.JLabel();
    txtTaxField = new javax.swing.JTextField();
    lblTotalDue = new javax.swing.JLabel();
    txtTotalDue = new javax.swing.JTextField();
    jpMenu = new javax.swing.JPanel();
    btnPlaceOrder = new javax.swing.JButton();
    btnExit = new javax.swing.JButton();
    lblPic = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Lunch Order");
    setResizable(false);

    jpMainCourse.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Main Course", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
    jpMainCourse.setFocusable(false);
    jpMainCourse.setLayout(new java.awt.BorderLayout());

    btnGpMain.add(rbHamburger);
    rbHamburger.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    rbHamburger.setSelected(true);
    rbHamburger.setText("Hamburger - $6.95");
    rbHamburger.setFocusable(false);
    rbHamburger.addItemListener(new java.awt.event.ItemListener()
    {
      public void itemStateChanged(java.awt.event.ItemEvent evt)
      {
        rbHamburgerItemStateChanged(evt);
      }
    });
    jpMainCourse.add(rbHamburger, java.awt.BorderLayout.PAGE_START);

    btnGpMain.add(rbPizza);
    rbPizza.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    rbPizza.setText("Pizza - $5.95");
    rbPizza.setFocusable(false);
    rbPizza.addItemListener(new java.awt.event.ItemListener()
    {
      public void itemStateChanged(java.awt.event.ItemEvent evt)
      {
        rbPizzaItemStateChanged(evt);
      }
    });
    jpMainCourse.add(rbPizza, java.awt.BorderLayout.CENTER);

    btnGpMain.add(rbSalad);
    rbSalad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    rbSalad.setText("Salad - $4.95");
    rbSalad.setFocusable(false);
    rbSalad.addItemListener(new java.awt.event.ItemListener()
    {
      public void itemStateChanged(java.awt.event.ItemEvent evt)
      {
        rbSaladItemStateChanged(evt);
      }
    });
    jpMainCourse.add(rbSalad, java.awt.BorderLayout.PAGE_END);

    layerPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add-ons ($.25/each)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
    layerPane1.setLayout(new java.awt.CardLayout());

    jpAddons.setLayout(new java.awt.BorderLayout());

    chkLettuce.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    chkLettuce.setSelected(true);
    chkLettuce.setText("Lettuce, tomato, and onions");
    chkLettuce.setFocusable(false);
    jpAddons.add(chkLettuce, java.awt.BorderLayout.PAGE_START);

    chkMayonnaise.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    chkMayonnaise.setText("Mayonnaise");
    chkMayonnaise.setFocusable(false);
    jpAddons.add(chkMayonnaise, java.awt.BorderLayout.CENTER);

    chkMustard.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    chkMustard.setSelected(true);
    chkMustard.setText("Mustard");
    chkMustard.setFocusable(false);
    jpAddons.add(chkMustard, java.awt.BorderLayout.PAGE_END);

    layerPane1.add(jpAddons, "card2"); 

    jpAddons2.setLayout(new java.awt.BorderLayout());

    chkPepperoni.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    chkPepperoni.setText("Pepperoni");
    chkPepperoni.setFocusable(false);
    jpAddons2.add(chkPepperoni, java.awt.BorderLayout.CENTER);

    chkSausage.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    chkSausage.setText("Sausage");
    chkSausage.setFocusable(false);
    jpAddons2.add(chkSausage, java.awt.BorderLayout.PAGE_START);

    chkMushrooms.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    chkMushrooms.setText("Mushrooms");
    chkMushrooms.setFocusable(false);
    jpAddons2.add(chkMushrooms, java.awt.BorderLayout.PAGE_END);

    layerPane1.add(jpAddons2, "card3");

    jpAddons3.setLayout(new java.awt.BorderLayout());

    chkCroutons.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    chkCroutons.setText("Croutons");
    chkCroutons.setFocusable(false);
    jpAddons3.add(chkCroutons, java.awt.BorderLayout.CENTER);

    chkBacon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    chkBacon.setText("Bacon Bits");
    chkBacon.setFocusable(false);
    jpAddons3.add(chkBacon, java.awt.BorderLayout.PAGE_START);

    chkBread.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    chkBread.setText("Bread Sticks");
    chkBread.setFocusable(false);
    jpAddons3.add(chkBread, java.awt.BorderLayout.PAGE_END);

    layerPane1.add(jpAddons3, "card4");

    jpSubTotal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Order Total", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
    jpSubTotal.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

    lblSubTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    lblSubTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblSubTotal.setText("Subtotal:");
    jpSubTotal.add(lblSubTotal);

    txtSubTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    txtSubTotal.setPreferredSize(new java.awt.Dimension(70, 20));
    jpSubTotal.add(txtSubTotal);

    lblTax.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    lblTax.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblTax.setText("Tax (8.25%)");
    jpSubTotal.add(lblTax);

    txtTaxField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    txtTaxField.setPreferredSize(new java.awt.Dimension(70, 20));
    jpSubTotal.add(txtTaxField);

    lblTotalDue.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    lblTotalDue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblTotalDue.setText("Total due:");
    jpSubTotal.add(lblTotalDue);

    txtTotalDue.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    txtTotalDue.setPreferredSize(new java.awt.Dimension(70, 20));
    jpSubTotal.add(txtTotalDue);

    btnPlaceOrder.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    btnPlaceOrder.setText("Place Order");
    btnPlaceOrder.setFocusable(false);
    btnPlaceOrder.setPreferredSize(new java.awt.Dimension(80, 23));
    btnPlaceOrder.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        btnPlaceOrderActionPerformed(evt);
      }
    });

    btnExit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    btnExit.setText("Exit");
    btnExit.setFocusable(false);
    btnExit.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        btnExitActionPerformed(evt);
      }
    });

    lblPic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myProj/resources/hamburger.png"))); // NOI18N
    lblPic.setLabelFor(rbHamburger);
    lblPic.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    lblPic.setFocusable(false);
    lblPic.setIconTextGap(0);
    lblPic.setPreferredSize(new java.awt.Dimension(100, 100));

    javax.swing.GroupLayout jpMenuLayout = new javax.swing.GroupLayout(jpMenu);
    jpMenu.setLayout(jpMenuLayout);
    jpMenuLayout.setHorizontalGroup(
      jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jpMenuLayout.createSequentialGroup()
        .addGroup(jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(btnPlaceOrder, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
        .addGap(18, 18, 18)
        .addComponent(lblPic, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
    );
    jpMenuLayout.setVerticalGroup(
      jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
      .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpMenuLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jpMenuLayout.createSequentialGroup()
            .addComponent(lblPic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
          .addGroup(jpMenuLayout.createSequentialGroup()
            .addComponent(btnPlaceOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGap(44, 44, 44)
            .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGap(24, 24, 24))))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(37, 37, 37)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jpMainCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jpSubTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(38, 38, 38)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jpMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(layerPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(35, 35, 35)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jpMainCourse, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
          .addComponent(layerPane1))
        .addGap(50, 50, 50)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jpMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(layout.createSequentialGroup()
            .addGap(9, 9, 9)
            .addComponent(jpSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(36, Short.MAX_VALUE))
    );

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void btnExitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnExitActionPerformed
  {//GEN-HEADEREND:event_btnExitActionPerformed
    // TODO add your handling code here:
    System.exit(0);
  }//GEN-LAST:event_btnExitActionPerformed

  private void btnPlaceOrderActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnPlaceOrderActionPerformed
  {//GEN-HEADEREND:event_btnPlaceOrderActionPerformed
    // TODO add your handling code here:
    DecimalFormat dollars = new DecimalFormat("$0.00");
        // declare double variables
        double hamPrice = 6.95;
        double pizPrice = 5.95;
        double salPrice = 4.95;
        
        double addons = 0;
        double subTotPrice;
        double taxPercent;
        double totalDuePrice;
        
        if (rbHamburger.isSelected())
        {
          
          if( chkLettuce.isSelected()) 
                addons += 0.25;
            
            if( chkMayonnaise.isSelected())
                addons += 0.25;
          
            if( chkMustard.isSelected())
                addons += 0.25;
            
           
            subTotPrice = hamPrice + addons;
                
            taxPercent = subTotPrice * 0.0825;
            totalDuePrice = subTotPrice + taxPercent;
        
            //display subtotal, tax and total due
            txtSubTotal.setText( dollars.format( subTotPrice ));
            txtTaxField.setText( dollars.format( taxPercent));
            txtTotalDue.setText( dollars.format( totalDuePrice ));
        }
        
        if (rbPizza.isSelected())
        {
          
          if( chkPepperoni.isSelected()) 
                addons += 0.25;
            
            if( chkSausage.isSelected())
                addons += 0.25;
          
            if( chkMushrooms.isSelected())
                addons += 0.25;
            
           
            subTotPrice = pizPrice + addons;
                
            taxPercent = subTotPrice * 0.0825;
            totalDuePrice = subTotPrice + taxPercent;
        
            //display subtotal, tax and total due
            txtSubTotal.setText( dollars.format( subTotPrice ));
            txtTaxField.setText( dollars.format( taxPercent));
            txtTotalDue.setText( dollars.format( totalDuePrice ));
        }
        
        if (rbSalad.isSelected())
        {
          
          if( chkCroutons.isSelected()) 
                addons += 0.25;
            
            if( chkBacon.isSelected())
                addons += 0.25;
          
            if( chkBread.isSelected())
                addons += 0.25;
            
           
            subTotPrice = salPrice + addons;
                
            taxPercent = subTotPrice * 0.0825;
            totalDuePrice = subTotPrice + taxPercent;
        
            //display subtotal, tax and total due
            txtSubTotal.setText( dollars.format( subTotPrice ));
            txtTaxField.setText( dollars.format( taxPercent));
            txtTotalDue.setText( dollars.format( totalDuePrice ));
        }
  }//GEN-LAST:event_btnPlaceOrderActionPerformed

  private void rbHamburgerItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_rbHamburgerItemStateChanged
  {//GEN-HEADEREND:event_rbHamburgerItemStateChanged
    // TODO add your handling code here:
    if (rbHamburger.isSelected())
        {
          jpAddons.setVisible(true);
          jpAddons2.setVisible(false);
          jpAddons3.setVisible(false);
          lblPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myProj/resources/hamburger.png")));
                    
          //Clear selection 
          txtSubTotal.setText("");
          txtTaxField.setText("");
          txtTotalDue.setText("");
          
          //Reset checkBox to default
          chkLettuce.setSelected(true);
          chkMayonnaise.setSelected(false);
          chkMustard.setSelected(true);
        }
  }//GEN-LAST:event_rbHamburgerItemStateChanged

  private void rbPizzaItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_rbPizzaItemStateChanged
  {//GEN-HEADEREND:event_rbPizzaItemStateChanged
    // TODO add your handling code here:
    if (rbPizza.isSelected())
        {
          jpAddons2.setVisible(true);
          jpAddons.setVisible(false);
          jpAddons3.setVisible(false);
          lblPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myProj/resources/pizza_slice.png")));
          
          //Clear selection 
          txtSubTotal.setText("");
          txtTaxField.setText("");
          txtTotalDue.setText("");
          
          //Reset checkBox to default
          chkPepperoni.setSelected(false);
          chkSausage.setSelected(false);
          chkMushrooms.setSelected(false);
        }
  }//GEN-LAST:event_rbPizzaItemStateChanged

  private void rbSaladItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_rbSaladItemStateChanged
  {//GEN-HEADEREND:event_rbSaladItemStateChanged
    // TODO add your handling code here:
    if (rbSalad.isSelected())
        {
          jpAddons3.setVisible(true);
          jpAddons.setVisible(false);
          jpAddons2.setVisible(false);
          lblPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myProj/resources/lettuce.png")));
          
          //Clear selection 
          txtSubTotal.setText("");
          txtTaxField.setText("");
          txtTotalDue.setText("");
          
          //Reset checkBox to default
          chkCroutons.setSelected(false);
          chkBacon.setSelected(false);
          chkBread.setSelected(false);
        }
  }//GEN-LAST:event_rbSaladItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LunchMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LunchMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LunchMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LunchMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LunchMenu().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnExit;
  private javax.swing.ButtonGroup btnGpMain;
  private javax.swing.JButton btnPlaceOrder;
  private javax.swing.JCheckBox chkBacon;
  private javax.swing.JCheckBox chkBread;
  private javax.swing.JCheckBox chkCroutons;
  private javax.swing.JCheckBox chkLettuce;
  private javax.swing.JCheckBox chkMayonnaise;
  private javax.swing.JCheckBox chkMushrooms;
  private javax.swing.JCheckBox chkMustard;
  private javax.swing.JCheckBox chkPepperoni;
  private javax.swing.JCheckBox chkSausage;
  private javax.swing.JPanel jpAddons;
  private javax.swing.JPanel jpAddons2;
  private javax.swing.JPanel jpAddons3;
  private javax.swing.JPanel jpMainCourse;
  private javax.swing.JPanel jpMenu;
  private javax.swing.JPanel jpSubTotal;
  private javax.swing.JLayeredPane layerPane1;
  private javax.swing.JLabel lblPic;
  private javax.swing.JLabel lblSubTotal;
  private javax.swing.JLabel lblTax;
  private javax.swing.JLabel lblTotalDue;
  private javax.swing.JRadioButton rbHamburger;
  private javax.swing.JRadioButton rbPizza;
  private javax.swing.JRadioButton rbSalad;
  private javax.swing.JTextField txtSubTotal;
  private javax.swing.JTextField txtTaxField;
  private javax.swing.JTextField txtTotalDue;
  // End of variables declaration//GEN-END:variables
}
